/**
 * Curated Lucide icon registry.
 *
 * Only the icons registered here are bundled (keeps tree-shaking intact).
 * The object key is the icon's public name — reference it kebab-cased in
 * templates via <app-icon name="triangle-alert"> (lucide normalizes the case).
 *
 * When a template needs a new icon: import its `<Name>Icon` here and add a
 * PascalCase entry. Never add emojis to templates — add an icon instead.
 */
import {
  // Navigation & chrome
  MenuIcon,
  XIcon,
  UserIcon,
  LogOutIcon,
  SettingsIcon,
  ChevronRightIcon,
  ChevronDownIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  PlusIcon,
  SearchIcon,
  UploadIcon,
  BellIcon,
  InfoIcon,
  CheckIcon,
  CheckCircleIcon,
  // Meta / data
  MapPinIcon,
  CalendarIcon,
  ClockIcon,
  IndianRupeeIcon,
  FileTextIcon,
  BanknoteIcon,
  WalletIcon,
  InboxIcon,
  // Status & flags
  TriangleAlertIcon,
  FlameIcon,
  ShieldIcon,
  ShieldCheckIcon,
  StarIcon,
  AwardIcon,
  TrophyIcon,
  RocketIcon,
  // Business domains (manpower)
  MonitorIcon,
  UtensilsIcon,
  UsersIcon,
  BrickWallIcon,
  WrenchIcon,
  HardHatIcon,
  // Services
  AirVentIcon,
  HouseIcon,
  PaintbrushIcon,
  ZapIcon,
  FactoryIcon,
  CctvIcon,
  ArmchairIcon,
  CableIcon,
  CogIcon,
  Building2Icon,
  // Value props
  BriefcaseIcon,
  TrendingUpIcon,
  GlobeIcon,
  // Contact & social
  PhoneIcon,
  MailIcon,
  FacebookIcon,
  LinkedinIcon,
  InstagramIcon,
  MessageCircleIcon,
  // Services & misc
  HammerIcon,
  SignpostIcon,
  RulerIcon,
  SparklesIcon,
  LockIcon,
  ClipboardListIcon,
  LightbulbIcon,
  HandshakeIcon,
  UserSearchIcon,
  LayersIcon,
  TargetIcon,
  EyeIcon,
  LogInIcon,
  UserPlusIcon,
  MegaphoneIcon,
  SaveIcon,
  SlidersHorizontalIcon,
  RefreshCwIcon,
  FolderIcon,
  FolderOpenIcon,
  PaperclipIcon,
  BarChart3Icon,
  ArrowUpIcon,
  ArrowDownIcon,
  CircleXIcon,
  CircleCheckIcon,
  PackageIcon,
  FuelIcon,
  CreditCardIcon,
  LandmarkIcon,
  SirenIcon,
  CircleHelpIcon,
  // Added during the inline-SVG sweep (V6)
  BookOpenIcon,
  ChevronLeftIcon,
  CircleIcon,
  CircleAlertIcon,
  ClipboardIcon,
  DownloadIcon,
  ExternalLinkIcon,
  FrownIcon,
  FunnelIcon,
  KeyRoundIcon,
  LoaderCircleIcon,
  PencilIcon,
  SendIcon,
  BanIcon,
  FilePlusIcon,
} from 'lucide-angular';

export const APP_ICONS = {
  Menu: MenuIcon,
  X: XIcon,
  User: UserIcon,
  LogOut: LogOutIcon,
  Settings: SettingsIcon,
  ChevronRight: ChevronRightIcon,
  ChevronDown: ChevronDownIcon,
  ArrowRight: ArrowRightIcon,
  ArrowLeft: ArrowLeftIcon,
  Plus: PlusIcon,
  Search: SearchIcon,
  Upload: UploadIcon,
  Bell: BellIcon,
  Info: InfoIcon,
  Check: CheckIcon,
  CheckCircle: CheckCircleIcon,

  MapPin: MapPinIcon,
  Calendar: CalendarIcon,
  Clock: ClockIcon,
  IndianRupee: IndianRupeeIcon,
  FileText: FileTextIcon,
  Banknote: BanknoteIcon,
  Wallet: WalletIcon,
  Inbox: InboxIcon,

  TriangleAlert: TriangleAlertIcon,
  Flame: FlameIcon,
  Shield: ShieldIcon,
  ShieldCheck: ShieldCheckIcon,
  Star: StarIcon,
  Award: AwardIcon,
  Trophy: TrophyIcon,
  Rocket: RocketIcon,

  Monitor: MonitorIcon,
  Utensils: UtensilsIcon,
  Users: UsersIcon,
  BrickWall: BrickWallIcon,
  Wrench: WrenchIcon,
  HardHat: HardHatIcon,

  AirVent: AirVentIcon,
  House: HouseIcon,
  Paintbrush: PaintbrushIcon,
  Zap: ZapIcon,
  Factory: FactoryIcon,
  Cctv: CctvIcon,
  Armchair: ArmchairIcon,
  Cable: CableIcon,
  Cog: CogIcon,
  Building2: Building2Icon,

  Briefcase: BriefcaseIcon,
  TrendingUp: TrendingUpIcon,
  Globe: GlobeIcon,

  Phone: PhoneIcon,
  Mail: MailIcon,
  Facebook: FacebookIcon,
  Linkedin: LinkedinIcon,
  Instagram: InstagramIcon,
  MessageCircle: MessageCircleIcon,

  Hammer: HammerIcon,
  Signpost: SignpostIcon,
  Ruler: RulerIcon,
  Sparkles: SparklesIcon,
  Lock: LockIcon,
  ClipboardList: ClipboardListIcon,
  Lightbulb: LightbulbIcon,
  Handshake: HandshakeIcon,
  UserSearch: UserSearchIcon,
  Layers: LayersIcon,
  Target: TargetIcon,
  Eye: EyeIcon,
  LogIn: LogInIcon,
  UserPlus: UserPlusIcon,
  Megaphone: MegaphoneIcon,
  Save: SaveIcon,
  SlidersHorizontal: SlidersHorizontalIcon,
  RefreshCw: RefreshCwIcon,
  Folder: FolderIcon,
  FolderOpen: FolderOpenIcon,
  Paperclip: PaperclipIcon,
  BarChart3: BarChart3Icon,
  ArrowUp: ArrowUpIcon,
  ArrowDown: ArrowDownIcon,
  CircleX: CircleXIcon,
  CircleCheck: CircleCheckIcon,
  Package: PackageIcon,
  Fuel: FuelIcon,
  CreditCard: CreditCardIcon,
  Landmark: LandmarkIcon,
  Siren: SirenIcon,
  CircleHelp: CircleHelpIcon,
  // Added during the inline-SVG sweep (V6)
  BookOpen: BookOpenIcon,
  ChevronLeft: ChevronLeftIcon,
  Circle: CircleIcon,
  CircleAlert: CircleAlertIcon,
  Clipboard: ClipboardIcon,
  Download: DownloadIcon,
  ExternalLink: ExternalLinkIcon,
  Frown: FrownIcon,
  Funnel: FunnelIcon,
  KeyRound: KeyRoundIcon,
  LoaderCircle: LoaderCircleIcon,
  Pencil: PencilIcon,
  Send: SendIcon,
  FilePlus: FilePlusIcon,
  Ban: BanIcon,
};
